import { test, expect } from '@playwright/test';
import { DASHBOARD } from '../login/login';

test.use({
    storageState: 'auth/client.json',
});

test('test', async ({ page }) => {
    await page.goto(DASHBOARD, { waitUntil: 'networkidle' });
    test.setTimeout(200000);

    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-click-workflow').click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Create New' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('textbox', { name: 'Enter workflow title' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('textbox', { name: 'Enter workflow title' }).fill('Asset Request Approval ');
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Asset Management' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-dml4u9-control > .react-select__value-container > .react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Asset Request' }).click();
    await page.waitForTimeout(800);
    await page.locator('div:nth-child(3) > .relative > .react-select-container > .react-select__control > .react-select__value-container > .react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Aprroval' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container.css-blprcc').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Manager Of' }).click();
    await page.waitForTimeout(800);
    await page.getByText('Select manager', { exact: true }).click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Owner' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Save' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-asset-management').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-my-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-raise-request-button').click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Nagesh Kadam' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-11wqccx-control > .react-select__value-container > .react-select__input-container').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'HDMI-Cable-1778649518273219' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-RR-AAR-priority-dropdown-button').click();
    await page.waitForTimeout(800);
    await page.getByText('High', { exact: true }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-RR-AAR-save-request-button').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByText('Nagesh Kadam').nth(1).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-AR-ARD-tab-workflow').click();
    await page.waitForTimeout(800);
    await page.getByText('Level 1Pending').click();
    await page.waitForTimeout(1500);
    await page.getByTestId('AM-AR-ARD-back-button').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-my-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-delete-button-0').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-cancel-delete-popup-confirm').click();
    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-click-workflow').click();
    await page.waitForTimeout(800);
    await page.locator('.relative > button').first().click();
    await page.waitForTimeout(800);
    await page.getByTestId('WF-CN-workflow-status-toggle').click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Update' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Create New' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('textbox', { name: 'Enter workflow title' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('textbox', { name: 'Enter workflow title' }).fill('Asset Request Apperoval');
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Asset Management' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-dml4u9-control > .react-select__value-container > .react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Asset Request' }).click();
    await page.waitForTimeout(800);
    await page.locator('div:nth-child(3) > .relative > .react-select-container > .react-select__control > .react-select__value-container > .react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Aprroval' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container.css-blprcc').click();
    await page.waitForTimeout(800);
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Specific User' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__value-container.react-select__value-container--is-multi > .react-select__input-container').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Nagesh Kadam' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Save' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-asset-management').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-my-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-raise-request-button').click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Nagesh Kadam' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-11wqccx-control > .react-select__value-container > .react-select__input-container').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'HDMI-Cable-1778649518273219' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-RR-AAR-priority-dropdown-button').click();
    await page.waitForTimeout(800);
    await page.getByText('High', { exact: true }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-RR-AAR-save-request-button').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByText('Nagesh Kadam').nth(1).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-AR-ARD-tab-workflow').click();
    await page.waitForTimeout(800);
    await page.getByText('Level 1Pending').click();
    await page.waitForTimeout(1500);
    await page.getByTestId('submenu-item-my-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-delete-button-0').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-cancel-delete-popup-confirm').click();
    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-click-workflow').click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Create New' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('WF-CN-Arrowleft icon').click();
    await page.waitForTimeout(800);
    await page.locator('.relative > button').first().click();
    await page.waitForTimeout(800);
    await page.getByTestId('WF-CN-workflow-status-toggle').click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Update' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Create New' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('textbox', { name: 'Enter workflow title' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('textbox', { name: 'Enter workflow title' }).fill('Asset Request Approval');
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Asset Management' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-dml4u9-control > .react-select__value-container > .react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Asset Request' }).click();
    await page.waitForTimeout(800);
    await page.locator('div:nth-child(3) > .relative > .react-select-container > .react-select__control > .react-select__value-container > .react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Aprroval' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container.css-blprcc').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'User Role' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-1gahky3-control > .react-select__value-container > .react-select__input-container').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Admin', exact: true }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.react-select__control--is-focused > .react-select__value-container > .react-select__input-container').click();
    await page.waitForTimeout(800);
    await page.getByText('Select User', { exact: true }).click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Nagesh Kadam' }).click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Save' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-asset-management').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-my-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-raise-request-button').click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__input-container').first().click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'Nagesh Kadam' }).click();
    await page.waitForTimeout(800);
    await page.locator('.react-select__control.css-11wqccx-control > .react-select__value-container > .react-select__input-container').click();
    await page.waitForTimeout(800);
    await page.getByRole('option', { name: 'HDMI-Cable-1778649518273219' }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-RR-AAR-priority-dropdown-button').click();
    await page.waitForTimeout(800);
    await page.getByText('High', { exact: true }).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-RR-AAR-save-request-button').click();
    await page.waitForTimeout(800);
    await page.getByTestId('submenu-item-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByText('Nagesh Kadam').nth(1).click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-AR-ARD-tab-workflow').click();
    await page.waitForTimeout(800);
    await page.getByText('Level 1Pending').click();
    await page.waitForTimeout(1500);
    await page.getByTestId('submenu-item-my-asset-requests').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-delete-button-0').click();
    await page.waitForTimeout(800);
    await page.getByTestId('AM-MAR-cancel-delete-popup-confirm').click();
    await page.waitForTimeout(800);
    await page.getByTestId('menu-item-click-workflow').click();
    await page.waitForTimeout(800);
    await page.locator('.relative > button').first().click();
    await page.waitForTimeout(800);
    await page.getByTestId('WF-CN-workflow-status-toggle').click();
    await page.waitForTimeout(800);
    await page.getByRole('button', { name: 'Update' }).click();
    await page.waitForTimeout(800);
});